trigger:
  branches:
    exclude:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

# Build
- script: |
    dotnet build Redstone.sln --configuration Release
  displayName: 'Build Redstone'

# Testing
- powershell: ./.azure/pipelines/test-solution.ps1
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: 'Test Redstone'

# Upload coverage
- script: |
    bash <(curl -s https://codecov.io/bash) -f ./tests/TestResults/Redstone.Common.Tests.xml
    bash <(curl -s https://codecov.io/bash) -f ./tests/TestResults/Redstone.NBT.Tests.xml
    bash <(curl -s https://codecov.io/bash) -f ./tests/TestResults/Redstone.Protocol.Tests.xml
    bash <(curl -s https://codecov.io/bash) -f ./tests/TestResults/Redstone.Server.Tests.xml
  displayName: 'Upload code coverage'

# Publish code coverage results as artifacts
- publish: $(System.DefaultWorkingDirectory)/tests/TestResults
  artifact: CoverageResults
  displayName: 'Publish code coverage results'
