version: '3.4'

services:
  redstone.server:
    image: ${DOCKER_REGISTRY-}redstoneserver
    build:
      context: .
      dockerfile: src/Redstone.Server/Dockerfile
    ports:
      - 25565:25565
    volumes:
      - ./bin/config/:/opt/redstone/config/
      - ./bin/data/:/opt/redstone/data/
