server:
  max-players: 100
  ip: ''
  port: 25565
  name: 'Redstone-Dev'
  description: 'An awesome Minecraft server powered by Redstone!'
  protocol-version: 754
  use-encryption: false
  mode: 'offline'
  debug: false
  reduced-debug-info: false
  flat-terrain: true
  allow-multiplayer-debug: true

game:
  mode: 'creative'
  seed: 0
  display-respawn-screen: true
  is-hardcore: false
  rendering-distance: 5
  level-name: 'redstone-world'
  world-map-format: 'anvil' # 'anvil' | 'redstone'

# Additionnal configuration