server:
  ip: ''
  port: 25565
  maxPlayers: 100
  description: 'An awesome Minecraft server powered by Redstone!'
  useEncryption: true
  mode: 'online'

game:
  mode: 'creative'

# Additionnal configuration