server:
  max-players: 100
  ip: ''
  port: 25565
  description: 'An awesome Minecraft server powered by Redstone!'
  use-encryption: false
  mode: 'offline'

game:
  mode: 'creative'
  seed: 0

# Additionnal configuration