server:
  max-players: 100
  ip: ''
  port: 25565
  description: 'An awesome Minecraft server powered by Redstone!'
  use-encryption: false
  mode: 'offline'
  debug: false
  reduced-debug-info: false
  flat-terrain: true

game:
  mode: 'creative'
  seed: 0
  display-respawn-screen: true
  is-hardcore: false
  rendering-distance: 5

# Additionnal configuration